---
# tasks file for tomcat
tasks:
    - name: Ensure tomcat is present
      apt:
       name: tomcat9
       update_cache: yes
       state: present
  
    - name: Ensure tomcat service is running
      service:
       name: tomcat9
       state: started